- index.html
info taken from https://groups.google.com/forum/#!topic/julia-users/BCmUTgL0WSk
(Sadly I will be unable to attend, as the dates conflict with my honeymoon.  But I thought people visiting juliacon.org should know when the dates are. :)
> Update with JuliaCon 2015 dates

- css/juliacon.css
- index.html
There are a lot of talks so it may be a little overwhelming as-is. Thoughts on
a better organizational structure are welcome. I'm thinking maybe each session
should be a javascript drop-down, so at first you get a high-level schedule and
you can click on each heading to get the talks in that session.
Also the sessions that end 10-minutes apart currently make it look like the
last talk is 10-minutes longer than it should be. We can either re-structure to
clarify that or just let it slide.
> RFC: adds the schedule currently in the master spreadsheet.

- _config.yml
- _data/workshops-sat.csv
- _data/workshops-wed.csv
- _layouts/abstracts.html
- index.html
- workshops.html
This PR adds abstracts/bios for workshops.  Once we settle the details, it shouldn't be hard to add the talks as a similar page(s).  I gave the workshops precedence for three reasons:
* Workshops are longer, and so people might want more info before committing time/$ to them.  It would be good to get the abstracts up as soon as practical.
* Some workshops need people to bring a computer.
* Self-interest -- I'm running one of the workshops :-)
Minor issue: Backquotes for literals in the Github-flavored markdown not being interpreted.  The additions to `_config.yml` were supposed to deal with this, but don't.
I'm new to Jekyll, so there may be newbie mistakes or suboptimalities.
> Add abstracts/bios for workshops.

- index.html
Four changes:
* Change conference end date from June 28 to June 27.
* Tighten paragraph slightly by replacing "but" with period. 
* Use "block rate" uniformly.  
* Tell people to use phone number, not website, if they are staying night of 6/23.
> Add instructions about using phone number if staying 6/23.  Change end date to June 27th.

- index.html
We decided that it'd be best to give people a bit more sleep and start the tutorial at 9:00 instead of 8:30.
@IainNZ @madeleineudell @joehuchette
> update juliaopt tutorial start time

- _config.yml
Jekyll 3.0 uses rouge by default, and pygments is no longer compatible. This shouldn't actually change the site, since we don't render any code blocks, but it will stop annoying warning emails from the GitHub Pages build service.
> remove custom highlighter configuration setting

- index.html
cc @ViralBShah 
This change adds a section that looks like this:
> Add sponsorship info section

- index.html
- workshops.html
Per issue [44](https://github.com/JuliaCon/JuliaCon2016/issues/44), this pull request adds a schedule of the days, and a page that describes the workshops.  
@jrevels: The unordered lists at the bottom of workshops.html render unindented.  They would look better if indented, but I don't know how to fix it.
> Add schedule of days to index, and page for workshops.

- workshops.html
Change adds presenter bios, revises Sander's abstract per email with him, adds Amit Murthy as a presenter.  To aid navigation, I put a short table of all workshops at the top with links.  When we have more timing information, we can add times to the table.
> Add workshop presenter bios.  

- abstracts.html
- index.html
This diff adds information about the talks.  The order is driven by Pontus' "random schedule" and the spreadsheets.  The program generates a schedule too from the spreadsheets, but I think we're not ready to settle on that.  I will post the program and sheets (.csv) later to the main repo.
Please look the list of talks over and tell me if any should be deleted, or there are ones in addition to Pontus' "random schedule".
> Add talk abstracts.

- abstracts.html
- index.html
- schedule.html
- workshops.html
This PR adds the tentative schedule for talks.  It also indicate which workshops are in morning or afternoon.
**Do we have confirmation** from Guy Steele and TIm Holy on which days they are talking?
Abstracts reordered to be consistent with schedule.  Unfortunately the current `gen.jl` interleaves them in the two-track situation.  Fixing that can wait for another day.
> Tentative schedule for talks.

- _includes/abstracts.html
- _includes/schedule.html
- workshops.html
Replace RataJulia with MusicIR and FrequonInvaders.
Move India into former location of FrequonInvaders.
Close gap that had MusicIR by shifting session up
and adding placeholder for Atcheson talk at end.
> Adjust for RataJulia cancellation; add rooms for workshop tracks.

- .travis.yml
- README.md
- script/build.sh
This PR should solve the incompatibility problem between the currently used plugins and GitHub pages. 
This is done by triggering automatic builds and deploys of the website from Travis Ci. 
Major changes:
1. Addition of  .travis.yml  to enable the automatic build and deployment
2. Add build script which will also test the website before deployment
3. Add information on this enahncement to the README.md file
> Add automatic build and deployment of the JuliaCon website

- 2018/all_talks.html
- 2018/assets/css/style.css
- 2018/lightning_talks.html
- 2018/talks.html
- 2018/workshops.html
- _data/2018_talks_workshops.yml
- _includes/main_nav.html
- _includes/talks_menu.html
- _layouts/2018speaker.html
cc: @essenciary 
Currently only workshops are populated, so the nav link goes to `workshops.html`. Should change to `talks.html` eventually. 
We've asked speakers to enter separate abstracts and talk descriptions, so I've added support for that. 
`talks/index.html` seems to be redundant, should probably be deleted?
> add workshops to the site

- _includes/earlybird.html
I think that URL is portable.
But someone should check it.
> Point to video playlist in header

- 2019/financial_assistance.html
- 2019/menubar.html
Resolves issue: [Add a new tab on the JuliaCon 2019 homepage for the financial assistance application](https://github.com/JuliaCon/JuliaCon2019/issues/26)
> Add menu item and page for financial assitance

- 2019/alert.html
This adds the CfP deadline and the last day for early bird tickets on the top of the banner.
Related issue: #164
> add deadlines on banner

- 2019/alert.html
Related issue: #164 
Perhaps having the deadlines in bold would be more noticeable :smiley: 
versus
> To bold the deadlines on top header

- 2019/cfp.html
- _config.yml
Uses the plugin "[Jekyll Redirect From](https://help.github.com/en/articles/redirects-on-github-pages)" to redirect `/2019/cfp/` to [https://pretalx.com/juliacon2019/](https://pretalx.com/juliacon2019/)
There was a conversation on the [#juliacon](https://julialang.slack.com/messages/C6J9D5QV6) slack channel where someone went to `/2019/cfp` but received last years content instead. This is just in case if anyone else ends up on `/2019/cfp` and gets confused with the CFP deadline. 
cc: @vchuravy
> Redirects /2019/cfp/ to Pretalx

- 2015/index.html
- 2016/index.html
- 2017/cfp.md
- 2017/coc.md
- 2017/index.html
- 2018/cfp.html
- 2018/coc.html
- 2018/tickets.html
- 2019/cfp.html
- 2019/tickets.html
- _includes/content.html
- staging/coc.md
Long overdue change. 
Related issues: [#33](https://github.com/JuliaCon/JuliaCon2019/issues/23) and #158 .  
Hopefully, anyone who had trouble contacting the committee would have seen this announcement thread on [discourse](https://discourse.julialang.org/t/juliacon-2019-july-21st-to-27th-in-baltimore-md-usa/18750/17).
> Update sitewide contact email

- 2019/alert.html
- 2019/assets/js/ticket-timer.js
This adds a countdown timer to the alert banner for pages `/2019/*`. 
`ticket-timer.js` counts down to May 10th for the end of Early bird ticket sales. The next time the page reloads, the countdown counts to July 22nd for regular ticket sales.
Here's an example:
What it will look like on the site:
I've used these sites as reference to make sure that the time remaining was consistent:
[Earlybird Countdown](https://www.timeanddate.com/countdown/vacation?iso=20190510T235959&p0=179&msg=Early+Bird&font=cursive)
[Regular Ticket Sale Countdown](https://www.timeanddate.com/countdown/launch?iso=20190722T235959&p0=419&msg=Regular+Sale&font=cursive)
> Add ticket sale countdown timer

- 2019/assets/css/style.css
- 2019/menubar.html
I've noticed that the waving flag gif was in the way of the menubar icon, shown below:
This fix hides the gif from mobile view:
> hide waving flag animation from mobile view in menubar

- 2020/alert.html
I came looking for this and it took too long to find it (it's at the very bottom of the pretalx site).  This is the trivial fix.
Bonus points if someone can javascriptedly make this count down (e.g., closes in 4 days 20 hours), but that someone is not going to be me.
> Add date/time for CfP deadline on front page

- 2020/alert.html
The link to the `tickets` page was broken. This should fix it.
> Fix the link to ticketing in the alert banner

- _layouts/default2020.html
As JuliaCon 2020 will be everywhere on Earth (🎉 ), the description in the meta tags needs to be updated.
> change meta description in layout

- 2020/menubar.html
Not sure what's the best option between https://pretalx.com/juliacon2020/schedule/ (it shows and empty schedule, which can confuse people) or https://pretalx.com/juliacon2020/schedule/#2020-07-29 (schedule of the first day of the conference)
> Add link to schedule on pretalx

- 2020/menubar.html
Instead of linking to pretalx for the schedule, link to the webapp agenda.  We'll probably want to think about how we link out to the web app more generally, but it's not fully ready yet.
> link to webapp

- _layouts/default2020.html
As it appears on facebook, twitter and linkedin, juliacon.org comes with a "Lisbon" thumbnail. Wondering if this is the right place to change that.
> Change default image?

- _layout/nav.html
This adds back the link to the pretalx
Note to @travigd and @aviks I see some recent changes: https://github.com/JuliaCon/www.juliacon.org/compare/45660d0..a852122
I did not migrate those. Could you check whether what was fixed still needs fixing and if so open an issue? thanks! 🙌
> pretalx link for proposals

- 2021/index.md
- _layout/nav.html
As promised in our JCON call today, here comes the PR that
* adds a Code of Conduct entry to the navigation bar and
* adds a Proceedings box to the main page.
> Add CoC to navbar + Add Proceedings box

- 2021/workshops.md
Replaced the markdown table with an HTML table to be able to add Bootstrap utility classes more easily and added borders (relates to https://github.com/JuliaCon/www.juliacon.org/issues/279).
> Replace markdown table with html table

- _layout/nav.html
remove sponsors (no need any more close to the event) and merch (there is already a top alert link). If needed merchandise info should go in as a content box in the site body.
> Add schedule to top menu.

- 2022/posters.md
1) Fixes posters by closing the div so it will appear again.
2) Adds poster presentations without links since I do not have access to the link information.
> Terminate grid div in posters.md

- 2023/index.md
Now the link should be directly clickable from the webpage.
> Fix financial assistance Google form link

- 2023/index.md
https://jolin.io does not work. Change it to https://www.jolin.io
> Fix jolin.io link to www.jolin.io

- 2020/index.md
- 2021/index.md
- 2022/index.md
- 2023/index.md
- _layout/head.html
- _layout/nav.html
- _layout/title_year.html
- config.md
- utils.jl
This PR improves a little bit the way the website renders the navbar and the title.
The current implementation presents difficulties when modifying the navbar for different events (e.g. future global JuliaCon or local JuliaCon events). With this PR, integrating new events into the main JuliaCon website becomes more manageable.
Previously, the HTML code relied on multiple `if else` statements for each year, which is not scalable for future JuliaCon and JuliaCon Local events. This PR addresses this issue by refactoring the code and introducing a new variable, `header`, in the `config.md` file. The rendering of the `header` itself is then handled by the `hfun_navbar` function defined in `utils.jl`. Additionally, two new functions, `insert_title_year` and `top_title_heading`, have been …
> [Improvement] Enhancing Navbar and Title Rendering for JuliaCon Events

- _layout/head.html
- config.md
- utils.jl
This PR removes many if statements from HTML files on the website and moves them in one place under `config.md` file. 
It makes it easier to control everything in one place and adds new extra features that were difficult before. For example, now it is easy to use different OpenGraph images per event. This fixes #414. Now each event can customize their OpenGraph metadata, alert messages on the top of the website, header, header colors, and all of it in one place!
@cityjumper
> Remove more if statements in html from the webiste

- 2023/committee.md
To acknowledge all of the help to comply with MIT's accessibility requirements and find a partner for subtitling.
> Update committee to include Flemming Holtorf

- config.md
- local/eindhoven2023/index.md
- local/eindhoven2023/pluto.md
- local/eindhoven2023/tickets.md
This PR removes links to the tickets and pluto workshop registration, changes the alert baner and hides the tickets box at the main page.
> JuliaCon Local Eindhoven: post event update

- config.md
#475 accidentally duplicated the entry Venue in the headers. Fixing it here.
> Deduplicate Venue entry in headers

- .github/workflows/cleanup.yml
I don't have access to settings of this repo, but judging by the fact [this build and deploy job](https://github.com/JuliaCon/www.juliacon.org/actions/runs/7630984939) ran on a commit on `main`, rather than `gh-pages`, my understanding is that we should run the clean-up job on `main`, not `gh-pages`.  For example https://juliacon.org/previews/PR498/2024/ is still there, even if #498 was closed and https://github.com/JuliaCon/www.juliacon.org/actions/runs/7630972233?pr=498 ran successfully.  Also, I have no idea what the `gh-pages` branch is for (maybe only created by this workflow?).
Side note, I believe the `franklin` and `main` branches should be protected, to prevented deletion, and `franklin` shouldn't allow direct pushes and require PRs
> [CI] Run previews cleanup on `main` branch

- .github/workflows/Deploy.yml
- .github/workflows/cleanup.yml
With this change all jobs pushing to the `main` branch (both for deplyoing the website and for cleaning up the previews) share the same concurrency group, to make sure we don't lose commits due to force pushing.
> [CI] Improve concurrency groups

- 2024/index.md
The certificate is only valid for https://evovest.com/, trying to open https://www.evovest.com/ gives an error message about invalid certificate on most browsers.
> Fix link for Evovest website

- 2024/index.md
- 2024/minisymposia.md
- 2024/schedule.md
- 2024/workshops.md
- config.md
This pull request incorporates the schedule onto various sections of the website. 
---
I've moved the 'schedule,' 'workshops,' and 'minisymposia' tabs into a single tab to prevent the navbar from extending excessively and displaying across two rows on smaller monitors.
---
I've also changed the order of items on the main page, placing the schedule directly after the tickets section.
> JuliaCon 2024: Add the schedule on the website

- 2024/venue-hotels.md
- config.md
This PR fixes #522
~As far as I understand there is no easy option to open a link created from `.md` files in a new tab. There is just no syntax for that :(~ Thanks to @lucaferranti the links now open in a new tab.
> Add a clarification regarding the social hub discount

- 2024/travel.md
This PR fixes #545
Would that be ok @cityjumper ? We've already had some options, e.g. NS bike rental. I kept them on the website, but I put the velorent as a first option
> Add velorent as an option for bike rental

- 2024/index.md
The link to the nominations Google form was incorrectly formatted I think.
> Fix link to the community prize nominations

- 2024/workshops.md
> Fix link to map of workshops venue

- .github/workflows/Deploy.yml
We broke the JuliaCon website on the first day because an error was suppressed.  The error had been live for a while, but a change to surrounding code caused it to move from minor annoyance to catastrophic.  This moves us to a stricter mode where such errors are not allowed at all.
> Set `suppress_errors=false` in Franklin build

- 2024/index.md
- config.md
This PR changes the alert description on the top of the website and also replaces the "buy tickets" button with the "watch recorded live stream" button on the main page.
> Post event 

- 2025/sponsor.md
Removed the "Additional Upgrades" and "FAQs" sections from the sponsorship page as requested.
Updated the page content to reflect only the relevant sponsorship details without extra information.
> Remove additional upgrades and FAQs

- 2024/index.md
This PR adds videos that I made for each day of Eindhoven 2024 on the main page.
The Day 2 is highlighted because it was a joint event with PyData :)
> Add movies on the main page eindhoven 2024

- 2025/index.md
- 2025/prize.md
Add 2025 Community Prize winners to the website.
> Add 2025 community prize winners
