_layouts/sched.html, index.html, sched.html
Simple page, separated in 3 sections, talks in alphabetical order by title. Links from main page. Can go back later and add hyperlinks if we want but I figured getting it up is first priority
=> Rough cut of schedule

sched.html
Well that happened in the meanwhile. https://github.com/shashi/Escher.jl/issues/13
=> Canvas.jl -> Escher.jl

index.html
The text was a bit jumbled up. (s/below/above/)
=> tweak sponsorship text

index.html
Change clarifies which days tickets apply to.
=> Clarify ticketing.

index.html
On suggestion from @IainNZ, I'm not publicly listing the location.
=> add dinner to schedule

index.html
As suggested in https://github.com/JuliaCon/JuliaCon2015/issues/45#issuecomment-107762654
=> Change wording and add contact information to accomodation

index.html
=> Added mossr Github link (Robert Moss)

index.html
=> Add eventbrite registration button

index.html
=> Add attendance blurb +  example talk areas

workshops.html
Adds times for workshops.  See [57](https://github.com/JuliaCon/JuliaCon2016/issues/57) for earlier discussion.
=> Add times for workshops, and format table more nicely.

css/juliacon.css, index.html, scss/juliacon.scss
At the request of @andreasnoack, I embedded a map to help people locate the Stata Center. The main page is now long enough that scrolling is annoying, so I also added a simple responsive navigation bar.
=> Add navigation bar and map

_includes/abstracts.html, _includes/schedule.html
Add authors names to schedule cells
Add titles to invited talks
Add room numbers.
Capitalize Kellyn Costa, Mariana Araujo
=> Add author names to schedule, add titles to invited talks, add room numbers

_includes/abstracts.html, _includes/schedule.html
Could someone proofread this PR and merge?  My flight is about ready to board.
=> Cancel Sisir talk

_includes/abstracts.html, _includes/schedule.html
=> add breakfast block to schedule

_includes/abstracts.html, _includes/schedule.html
Can someone proofread and push?  Excel seems to have gratuitously changed trailing whitespace on a few lines.
=> Remove cancelled Verzani talk.

_includes/abstracts.html, _includes/schedule.html, workshops.html
Move Lora talk from late Friday to late Thursday track 2.
Capitalize "G" in Shashi Gowda's name.
Add link to Robison workshop materials
=> More website changes for Wednesday

2017/coc.md, 2017/index.html
=> Add link to CoC

2017/cfp.md, 2017/index.html
Re https://github.com/JuliaCon/JuliaCon2017/issues/11 
Let's do a last round of review. I will send out notifications tomorrow.
The submission form itself is available at https://goo.gl/forms/I0ssJvpQKm2NyCmg1
=> Add call for proposal

2017/index.html
cc: @andreasnoack I hope I haven't forgotten anyone.
@shashi I didn't found abetter way to get the layout I wanted. I hope this is alright, but feel free to change it.
=> add comittee to website

_data/jc2017/lts.yml, _data/jc2017/talks.yml, _data/jc2017/workshops.yml
Done automatically with a Julia script.
=> Capitalize titles

_data/jc2017/lts.yml
I have updated my bio and made it consistent with the other speaker's bio.
=> Updated description of the speaker and better grammar

_data/jc2017/lts.yml
=> Add slides for DataStreams and Nulls.jl

2018/index.html
Is the reference to ethnicity acceptable?
=> Add explicit reference to national and ethnic origin

2018/tickets.html, _includes/main_nav.html
[the table at the end needs styling]
cc: @essenciary
=> add ticket page

_includes/content.html
=> add Tim and Gil as keynote speakers

_data/2018_talks_workshops.yml
=> Remove Christoph Ortner from numerical analysis workshop

2018/schedule.html
Add names of days to dates on schedule.
=> Add day names to schedule

_data/2018_talks_workshops.yml
My edits on sched got lost when I submitted them. :-o Now I've updated everything but the title there.
=> update JuliaDB talk

_data/2018_talks_workshops.yml
Should have been done ages ago, I assume that something needs to be done on the Sched side as well?
=> Update machine learning workshop authors

_includes/content.html
=> Retrospectively clarify identity of the real diversity chair

2019/sponsorship.html
Resolves issue: [Add university partnerships to Sponsor page on website](https://github.com/JuliaCon/JuliaCon2019/issues/27)
=> University Partnerships in Diversity section description

2019/financial_assistance.html
@Bubblemelon Does this look alright? It seems like the special dots aren't rendering on the website.
=> Update financial assistance page

2019/committee.html
After discussions in person and at the call today.
=> Minor chair re-shuffling

2019/assets/css/style.css, 2019/menubar.html, 2019/volunteer.html
This PR adds a volunteer page and adds css for green text. 
Related issue: [#31](https://github.com/JuliaCon/JuliaCon2019/issues/31)
Note: I have removed the word **an** as [discussed](https://github.com/JuliaCon/JuliaCon2019/issues/31#issuecomment-478112908).
=> add volunteer page

2019/content19.html
=> Fix some typos in content19.html

2019/content19.html, 2019/index.html
Related issue: #175 . See issue :eyes: for screenshot with updates.
=> Update venue address

2019/alert.html, 2019/assets/css/style.css
This adds the request mentorship link to the top of every page. Related issue [#40](https://github.com/JuliaCon/JuliaCon2019/issues/40)
=> Add Request Mentorship link to Alert Banner

2020/menubar.html
=> Add ticket and cfp links to the menu

2020/tickets.html
Made the Ticket ordering window bigger
=> Made the Ticket ordering window bigger

2020/tickets.html
Supposedly "upto" is not an actual word in the dictionary https://en.wiktionary.org/wiki/upto
=> Fixed spelling on ticket page

2020/footer.html
Don't want to break the build in case things have changed. Leaving it for somebody else to merge.
=> Brought it into 2020 :)

2020/content.html, 2020/faq.html, 2020/index.html, 2020/tickets.html, 2020/volunteer.html
A few copy edits.  Mostly removing some things that don't make sense anymore, and adding a form for virtual volunteers.
=> feat: various copy edits, add virtual volunteer form

2020/accessibility.html, 2020/menubar.html
Comments and suggestions welcome. 
cc: @aviks @xorJane
=> RFC: Add JuliaCon accessibility doc

2021/assets/css/style.css, 2021/index.html
=> Fix hero header image

utils.jl
=> windows filepath in regex

_layout/head.html
It's always _good_ to have the call-to-actions being... very... actiony (i.e., using verbs)
=> Free Tickets -> Register for Free

2021/committee.md
Hey @JuliaCon/committee2021, adding this PR to ensure the process for joining the committee is more open than it is now. I will add a form for nominations and get you all access if you think this looks good. 
CC @jiahao
=> Add process for joining the JuliaCon Committee

2021/sponsor.md
=> Update sponsor tiers

2021/workshops.md
I found this confusing at first
=> Rename "Talk title" to "Workshop title"

2021/index.md
@alanedelman pointed this out.
=> Make workshop start date explicit

2021/workshops.md
Adds the "table" class to the markdown generated table so Bootstrap can style it. Fixes https://github.com/JuliaCon/www.juliacon.org/issues/279
=> Add table class to fix padding issue

2021/experiences.md, 2021/posters.md
I thought it might be good to have a grid layout for the posters. It looks like this:
and resizes like this:
Just an idea, you might want to develop it further or not... :)
=> Try grid layout for posters?

2021/posters.md
Added an entry for my poster, which was not on the list
=> Added missing poster

2021/posters.md
This helps us coordinate on Gathertown, marking each poster slot with a number corresponding to here.
=> Update posers with numbers.

2021/posters.md
=> Fix numbering error

2022/cfp_es.md
Thank you to @miguelraz for the translation!
=> Create Spanish CFP

2022/cfp_pt.md
CFP translation to Portuguese.
PR by me and @fausto-mpj.
=> Add 2022 Brazilian Portuguese CFP

2022/posters.md
Usually we link to the pretalx reviews, but perhaps a direct link to the YouTube talk is better?
=> Add links to YouTube videos for posters

2022/prize.md
I do live in Germany at the moment, but haven't adjusted my name to German-like spelling 🙂
=> Update spelling of names

2023/committee.md
No longer have a Twitter. Better title perhaps, not sure exactly what it should be.
=> Update Committee Info

2023/index.md
=> Add co-located conferences

local/eindhoven2023/cfp.md
This PR clarifies Q&A session and duration
=> Clarify Q&A duration

local/eindhoven2023/venue.md
It looked like there were 6 hotels suggested, it took me a bit to realise the even items in the list were the addresses of the odd items.
=> Less confusing addresses for hotels in Eindhoven

config.md, local/eindhoven2023/index.md
The dates/times/location are not certain yet, lets hide it for now so no to confuse people.
=> JuliaCon Local Eindhoven 2023: hide Pluto workshop for now

config.md, local/eindhoven2023/diversity.md, local/eindhoven2023/index.md, local/eindhoven2023/pluto.md, local/eindhoven2023/program.md, local/eindhoven2023/tickets.md
This PR has final preparations, which include the program!!, diversity scholarship, Pluto workshop announcement and some other minor stuff.
@cityjumper
=> JuliaCon Local Eindhoven 2023: We are going live!

config.md, local/eindhoven2023/coc.md, local/eindhoven2023/pluto.md, local/eindhoven2023/program.md
This PR adds more info about the Pluto Workshop and also fixes the pretalx preview layout on small screens
=> JuliaCon Local Eindhoven 2023: update Pluto workshop info

2024/index.md
We are considering a different venue for JuMP-dev next year
=> Remove co-location with JuMP-dev

2024/index.md, config.md, utils.jl
Also, d29964858aee6021290a8ab260eff9c44995fb1f removed the description of the event. Adding it back here.
@ranjanan
=> Improve the year navigation bar

2024/index.md, config.md
Given #454 , should we also remove the JuMP track from pretalx?
=> add cfp 2024

2024/index.md
15th January 2023 to 15th January 2024
=> Update deadline to the future

2024/index.md
=> improve capitalisation

2024/index.md, 2024/venue.md
=> JuliaCon 2024 Eindhoven: adjust the links to the stadium

2024/index.md
=> JuliaCon 2024 Eindhoven: adjust the title of the event

2024/dei.md, 2024/index.md
=> first draft of dei page

.github/workflows/Deploy.yml, .github/workflows/cleanup.yml, .github/workflows/pr_comment.yml, config.md
Reverts JuliaCon/www.juliacon.org#483
=> Revert "Revert "Add preview""

2024/sponsor.md
=> Change wording for the sponsor page

_layout/page_foot.html
wow fons what an amazing contribution unbelievable
=> update copyright year

2024/index.md, utils.jl
=> JuliaCon 2024 Eindhoven: make CFP bigger

2024/minisymposia/hpc.md
Hi! I have submitted the proposal for the HPC minisymposium. I would like to update the scheduled list of speakers slightly (including one co-author).
=> Update HPC minisymposium

2024/committee.md
=> Add names and edit committee titles

2024/sponsor.md
As discussed with Mark and Skylar
=> Bump scholarship numbers

2024/index.md, config.md
I don't really like how it currently looks, but I'm not a designer, so I'm open to suggestions to improve it :)
=> Add ticket links

2024/sponsor.md
Add exhibition table to copper sponsorship
=> Add exhibition table to Copper

_css/style.css, _layout/page_foot.html
=> Update social media buttons

2024/workshops.md
Closes #532
Thank you @cormullion!
=> Improve Docs Workshop wording

2024/tickets.md, config.md
This PR changes the ticket prices to be consistent with the ones on Ticket Tailor
=> Change ticket prices from early bird to non-early bird

2024/accessibility.md
I am including guidelines for presentation, need review and discussion (proper templates will also be provided). @ranjanan @rayegun
=> Update accessibility.md for presentations guidelines

2024/accessibility.md, config.md
This PR makes various changes to the Accessibility page suggested by @cormullion
=> Improve the Accessibility page

2024/jobboard.md, config.md
Move some of the items in the top ribbon into one because otherwise it would be a bit much. 
Job Board looks like:
=> Add Job Board

2024/index.md, config.md
- Adds a button to increase the visibility of the Schedule
- Improves clarity of one of the menu entries.
=> Miscellaneous updates 

2024/tickets.md
=> Update information about ticket prices.

2024/travel.md
This PR adds [Eindhoven Travel Guide](https://www.youtube.com/watch?v=Jojzpiu2g3w) video for the travel section.
=> Add eindhoven travel guide video

2024/tickets.md
=> Streamline tickets page, make ticket purchasing button more obvious

_css/style.css
=> Increase buttoness of buttons. Darken and drop shadow on hover.

2024/coc.md
=> Add in-person language to CoC

2024/volunteer.md
Mention the reviewers registration form on the volunteer page.
=> proceedings reviewers form on volunteering page

2024/committee.md, 2024/dei.md, 2024/index.md
=> Close scholarship applications

2024/travel.md
=> add extra information about ticket free journeys

2024/index.md, 2024/workshops.md
This PR adds more information about the upcoming workshops, such as location, av info, catering info, etc
=> Add more information about the workshops

2024/index.md
=> Fix 404 psv link

2024/index.md, 2024/tickets.md, config.md
=> Embed ticketing in website

2024/dei.md
Add mentor/mentee information to the website so we can link to it for the email blasts.
=> Add mentor/mentee information.

2024/hackathon.md, 2024/index.md, config.md
Added Hackathon info to the top header. 
Started with a separate hackaton page, but needs more information
=> Add some hackathon info

2024/store.md, config.md
Items would be available to be collected on-site
=> Create a JuliaCon 2024 Merchandise Store

2024/hackathon.md
=> Suggest Hackathon details

2024/tickets.md
=> One week out

2024/activities.md
=> added links from the video

2024/index.md
Mosè noticed these were unbalanced.  Franklin complains about this as a warning, but we believe it should be an error.
=> Match closing `@@`

config.md
=> Change store to spreadshop store

2024/index.md, 2024/prize.md, config.md
=> add 2024 prize

2025/index.md
Just fixes a wee mistake I noticed. Since it's so minor I did not build the site locally.
=> Update mention of the upcoming Juliacon

local/paris2025/index.md, local/paris2025/program.md
=> [paris25] minor updates

local/paris2025/index.md
=> [paris25] fix venue link

config.md, local/paris2025/cfp.md
=> [paris25] advertise CFP

2025/index.md
=> Add Letter of Invitation to landing page

2025/index.md
add preliminary info about location
=> add preliminary info about location

2025/index.md
=> Add travel funding form

2025/tickets.md, config.md
=> Publish tickets

2025/tickets.md
=> Update tickets.md, lower 3-day price

config.md, local/paris2025/cfp.md, local/paris2025/tickets.md
=> [paris25] Add link to ticketing

config.md
=> Proper fix workshop URL path in configuration

2025/index.md
=> Add JuliaHub as a Diamond sponsor

2025/housing.md
=> Add faq questions

config.md
Reverts JuliaCon/www.juliacon.org#675
=> Revert "alert to complete julia survey"

2025/accessibility.md, 2025/index.md
Hi @ranjanan there was a typo in the accessibility page, I fixed it (now we can access the pdf and pptx files)
Best,
Leticia
=> Fix typo in accessibility page

2025/index.md
=> Community Prize form

2025/index.md
=> Update Community Prize box color to green

local/paris2025/index.md, local/paris2025/tickets.md
=> [paris25] close grant application form

2025/accessibility.md
=> Fix accessibility files path

2025/index.md
=> social media template

2026/index.md, 2026/minisymposia_cfp.md, config.md
=> Link the CfP from the main page

local/paris2025/index.md
=> [paris25] add hackathon info
